export default {
  POSITION: 'position',
  SCALE: 'scale',
  ROTATION: 'rotation',
  ANCHOR_POINT: 'anchor point',
  OPACITY: 'opacity',
  POSITION_X: 'position x',
  POSITION_Y: 'position y',
  POSITION_Z: 'position z',
  ELLIPSE_POSITION: 'ellipse position',
  ELLIPSE_SIZE: 'ellipse size',
  RECTANGLE_POSITION: 'rectangle position',
  RECTANGLE_SIZE: 'rectangle size',
  RECTANGLE_RADIUS: 'rectangle radius',
  STAR_INNER_RADIUS: 'star inner radius',
  STAR_INNER_SIZE: 'star inner size',
  STAR_OUTER_RADIUS: 'star outer radius',
  STAR_OUTER_SIZE: 'star outer size',
  STAR_POSITION: 'star position',
  STAR_RADIUS: 'star radius',
  STAR_POINTS: 'star points',
  OFFSET_PATHS_AMOUNT: 'offset paths amount',
  OFFSET_PATHS_MITER_LIMIT: 'offset paths miter limit',
  ROUNDED_CORNERS_RADIUS: 'rounded corners radius',
  TRIM_PATH_START: 'trim path start',
  TRIM_PATH_END: 'trim path end',
  TRIM_PATH_OFFSET: 'trim path offset',
  PUCKER_AND_BLOAT_AMOUNT: 'pucker and bloat amount',
  TWIST_ANGLE: 'twist angle',
  TWIST_CENTER: 'twist center',
  GRADIENT_STROKE_START: 'gradient stroke start',
  GRADIENT_STROKE_END: 'gradient stroke end',
  GRADIENT_STROKE_OPACITY: 'gradient stroke opacity',
  GRADIENT_STROKE_MITER_LIMIT: 'gradient stroke miter limit',
  GRADIENT_STROKE_WIDTH: 'gradient stroke width',
  GRADIENT_FILL_START: 'gradient fill start',
  GRADIENT_FILL_END: 'gradient fill end',
  GRADIENT_FILL_OPACITY: 'gradient fill opacity',
  FILL_COLOR: 'fill color',
  FILL_OPACITY: 'fill opacity',
  ZIG_ZAG_POINTS: 'zig zag points',
  ZIG_ZAG_RIDGES: 'zig zag ridges',
  ZIG_ZAG_SIZE: 'zig zag size',
  STROKE_COLOR: 'stroke color',
  STROKE_OPACITY: 'stroke opacity',
  STROKE_WIDTH: 'stroke width',
  SHAPE_TRANSFORM_ANCHOR_POINT: 'shape transform anchor point',
  SHAPE_TRANSFORM_OPACITY: 'shape transform opacity',
  SHAPE_TRANSFORM_POSITION: 'shape transform position',
  SHAPE_TRANSFORM_ROTATION: 'shape transform rotation',
  SHAPE_TRANSFORM_SKEW_AXIS: 'shape transform skew axis',
  SHAPE_TRANSFORM_SKEW: 'shape transform skew',
  REPEATER_COPIES: 'repeater copies',
  REPEATER_OFFSET: 'repeater offset',
  REPEATER_TRANSFORM_ANCHOR_POINT: 'repeater transform anchor point',
  REPEATER_TRANSFORM_POSITION: 'repeater transform position',
  REPEATER_TRANSFORM_ROTATION: 'repeater transform rotation',
  REPEATER_TRANSFORM_SCALE: 'repeater transform scale',
  REPEATER_TRANSFORM_START_OPACITY: 'repeater transform start opacity',
  REPEATER_TRANSFORM_END_OPACITY: 'repeater transform end opacity',
}
