export default {
	SHAPE: 'sh',
  RECT: 'rc',
  ELLIPSE: 'el',
  STAR: 'sr',
  FILL: 'fl',
  GFILL: 'gf',
  GSTROKE: 'gs',
  STROKE: 'st',
  MERGE: 'mm',
  TRIM: 'tm',
  TWIST: 'tw',
  GROUP: 'gr',
  REPEATER: 'rp',
  ROUNDEDCORNERS: 'rd',
  OFFSETPATH: 'op',
  PUCKERANDBLOAT: 'pb',
  ZIGZAG: 'zz',
  TRANSFORM: 'tr',
}